info:
  head: head
  body: body
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false

#tomcat      
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /tx-admin

#spring    
spring:
  profiles:
    active: dev
  #视图
  #freemarker:
    #suffix: .html
    #request-context-attribute: request
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
      file-size-threshold: 0
#mybatis
mybatis:
  mapper-locations: classpath*:mapper/*/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cn.tianxia.admin.project
    
#打印日志
logging:
  config: classpath:log4j.yml 
